name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "main" ]
# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
    testing_ubuntu:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
          # - uses: actions/checkout@v3
          - name: testing_lnx
            run: |
               cd ..
               python -m unittest test_geometry.py
                
    testing_windows:
      runs-on: windows-latest
      steps:
        - name: testing_win
          run: |
             cd ..
             python -m unittest test_geometry.py
