name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  testing_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
   
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Run tests on Linux
        run: python -m unittest test_geometry.py

  testing_windows:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Run tests on Windows
        run: python -m unittest test_geometry.py
